# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

# LinkedIn
LINKEDIN_APP_ID: yzv2uqdo4vot
LINKEDIN_APP_SECRET: lz2AbbRg0uN1DgMW

# AWS S3
PRODUCTION_AWS_BUCKET: craft-production
DEVELOPMENT_AWS_BUCKET: craft-development
STAGING_AWS_BUCKET: craft-staging
AWS_ACCESS_KEY_ID: AKIAJXQS5ORNP3JCZHBQ 
AWS_SECRET_ACCESS_KEY: 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 


# Others
CRUNCHBASE_API_KEY: bqs54zazy2as6xg8qvc7mdbb
CRUNCHBASE_API_KEY_V2: 3a6d930d3684426eeec4f2304858a3f7
BING_API_KEY: iOFmIMvlUIE2FidjxbIjhgFfpwJoDCZctZmUabGO/Kk
TWITTER_API_KEY: 1j2G7SfP5rIXS3hh5FSZlcDhz
TWITTER_SECRET:  h3JhE0mM5KHSVpOZhorTpeXqgTafFUpli5Vgniv7JMvYjrOeKy
TWITTER_ACCESS_TOKEN: 2432096425-4iMZbKPkacRHrNuOi5VVgEqdIK5QmWecqFJAnuP
TWITTER_ACCESS_TOKEN_SECRET: hf4HzKGgO0LtmcNXuXixogw9F7lscj6p50155TR8tTLyU
TWITTER_BEARER_TOKEN: AAAAAAAAAAAAAAAAAAAAAMzSUwAAAAAAH%2FlAmyRSbGg77p1BzyxbSHB%2B%2BpY%3D93UJxes3eDbUiH7IFZE3hpV6W3ZJEy1Q3h4Th4yIKywQSzqQGr
